### ISSUE TITLE
Saavn Downloader

### ISSUE THREAD

**Issue by pdave1979** [naqushab/saavn-downloader-extension#23] opened 2019-08-01 04:19 UTC
I have added saavn Downloader into my chrome extension. But suddenly stopped to download songs. Not getting any error but only showing "Downloading Album Art" status at below saavn page. Please help.

**Comment by naqushab** [comment] 2020-06-22 22:39
Duplicate of #30

**Closed by naqushab** 2020-06-22 22:39 UTC
