### ISSUE TITLE
SAAVN IS CHANGE NOW IS JIOSAAVN

### ISSUE THREAD

**Issue by SWARUP24** [naqushab/saavn-downloader-extension#8] opened 2018-12-02 20:35 UTC
SAAVN IS CHANGE NOW IS JIOSAAVN PLEASE FIXED THIS ISSUE

**Comment by OmkarK45** [comment] 2018-12-04 08:13
Use this updated ext https://github.com/justiriser/JioSaavn-Downloader-Chrome-Extension/blob/master/README.md

**Comment by naqushab** [comment] 2018-12-04 18:44
The issue is now fixed. Thanks to @justiriser

**Closed by naqushab** 2018-12-04 18:44 UTC
