### ISSUE TITLE
Download Problem

### ISSUE THREAD

**Issue by ravi0239** [naqushab/saavn-downloader-extension#70] opened 2021-04-11 12:34 UTC
Songs Not Downloaded, I will try to downloading song (SORRY,THAT'S AN ERROR) Showing...

**Comment by ghost** [comment] 2021-04-11 13:20
Related issue 

#69

**Comment by tuhinpal** [comment] 2021-04-12 15:31
You tried in mobile? Look, this extension's download feature only works with pc. So, share more details for better inspection

**Comment by tuhinpal** [comment] 2021-06-30 18:03
Closing this issue, feel free to reopen it if the issue is not resolved.

**Closed as completed by tuhinpal** 2021-06-30 18:03 UTC
