### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ReptileLDN** [naqushab/saavn-downloader-extension#3] opened 2018-07-20 23:15 UTC
Downloads small file versions of the mp3 but not full tracks, please fix.

**Comment by ReptileLDN** [comment] 2018-07-21 12:14
https://github.com/naqushab/saavn-downloader-extension.git

**Comment by naqushab** [comment] 2018-07-21 12:37
Nope, the song that you're trying to download. I see the extension is working fine for me. Like for this  [song](https://www.saavn.com/s/song/hindi/Nawabzaade/High-Rated-Gabru/Hz8YZgJFcWY) it is working fine.

**Comment by ReptileLDN** [comment] 2018-07-21 12:44
https://www.saavn.com/s/album/hindi/Kalia-1997/pQoC89nA,OA_

**Comment by naqushab** [comment] 2018-07-21 13:03
All songs are downloading fine for me. 
I am using Chrome browser. Have you tried downloading the songs individually? Is this problem a url specific or is supposed to happen on all urls?

**Comment by ReptileLDN** [comment] 2018-07-21 21:14
Sorry for the late reply just got home from work
I tried downloading the files individually but only the first track fully downloads the rest download at a smaller size 100 kb per mp3 file, really weird, not the full track just 100kb equivalent of the mp3.
It happens specific urls like this one as well: https://www.saavn.com/s/album/hindi/Mard-1985/DpkX19nBD2I_ + https://www.saavn.com/s/album/hindi/Pardesi-Babu-1998/QBKZKEzZqFA_ both arent working for me at all, same with the high rated gabru, only smaller files download.
I have even tried using an asian ip and nothing changes.

**Comment by naqushab** [comment] 2018-07-22 17:48
The extension is not IP dependent. I request you to try on a fresh install Chrome or Firefox and see if the problem persists. Also, try downloading in lower quality(128kbps for example) and see if that helps. 
For me, the issue is non-reproducible. So I am closing this issue till anyone else reports or I get any other details.

**Closed by naqushab** 2018-07-22 17:48 UTC
