### ISSUE TITLE
Not Working !

### ISSUE THREAD

**Issue by OmkarK45** [naqushab/saavn-downloader-extension#9] opened 2018-12-03 09:33 UTC
Hey thanks buddy for updating the extension. Appreciate the effort but the new extension is not downloading complete song from jiosaavn. It is downloading only some part of it (100kB to 200kB). Hope you fix that.
![capture](https://user-images.githubusercontent.com/45557594/49365375-a1249e80-f70c-11e8-99ce-e29a0e87a635.JPG)

**Comment by tamilmusiq** [comment] 2018-12-03 09:38
is this extension is updated? after saavn changed to jiosaavn?

**Comment by OmkarK45** [comment] 2018-12-03 09:41
Yes

**Comment by OmkarK45** [comment] 2018-12-03 09:42
https://github.com/justiriser/JioSaavn-Downloader-Chrome-Extension

**Comment by OmkarK45** [comment] 2018-12-03 12:13
Update : Its working now

**Comment by tamilmusiq** [comment] 2018-12-03 12:51
Thanks working fine 👍

**Comment by naqushab** [comment] 2018-12-04 18:45
The issue is now fixed. Thanks to @justiriser

**Closed by naqushab** 2018-12-04 18:45 UTC

**Comment by babz1989** [comment] 2018-12-17 18:15
I'm still getting this error even with @justiriser fix

**Comment by naqushab** [comment] 2018-12-18 01:48
Can you please share the link from where you are trying to download the
music?

**Comment by babz1989** [comment] 2018-12-18 15:43
https://www.saavn.com/search/long%20drive
