### ISSUE TITLE
not able to download songs from this extension

### ISSUE THREAD

**Issue by Farzan1234** [naqushab/saavn-downloader-extension#28] opened 2019-11-26 05:37 UTC
http://justiriser.blogspot.com/2018/12/download-songs-from-jiosaavncom-to-mp3.html

**Comment by justiriser** [comment] 2019-11-26 17:27
> http://justiriser.blogspot.com/2018/12/download-songs-from-jiosaavncom-to-mp3.html

did u downloaded the zip file... proceed with the steps mentioned... it should work

**Comment by naqushab** [comment] 2020-06-22 22:44
Duplicate of #30

**Closed by naqushab** 2020-06-22 22:44 UTC
