### ISSUE TITLE
saavn changed to jiosaavn

### ISSUE THREAD

**Issue by tamilmusiq** [naqushab/saavn-downloader-extension#7] opened 2018-12-02 14:58 UTC
extension working fine before its had changed. after changed to jiosaavn extension does not works. Please udpate it

**Comment by sharan-aadarsh** [comment] 2018-12-04 17:39
Same issue

**Comment by naqushab** [comment] 2018-12-04 18:44
@sharan-aadarsh @tamilmusiq  The issue is now fixed. Thanks to @justiriser

**Closed by naqushab** 2018-12-04 18:44 UTC
